#!/usr/bin/env python3
"""Turn a plaintext term list into the SHA-256 digest file the Worker loads.

The repo is public. The plaintext input is NEVER committed — write it to a
path outside the repo, run this, commit only the output.

Usage:
    python3 scripts/hash_terms.py ~/terms.txt worker/data/blocked.txt
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# The policy modules import each other bare, matching the layout the
# deployed Worker roots itself at. See scripts/run_tests.py.
sys.path.insert(0, str(REPO_ROOT / "worker" / "src"))

from matching import digest  # noqa: E402
from normalize import normalize, strip_nonalnum  # noqa: E402

SUBSTR_MINLEN = 5


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2

    source, dest = Path(sys.argv[1]), Path(sys.argv[2])

    if source.resolve().is_relative_to(REPO_ROOT):
        print(f"ERROR: {source} is inside the repo. The plaintext term "
              "list must never be committed. Move it elsewhere.")
        return 1

    try:
        raw = source.read_text(encoding="utf-8-sig")
    except OSError as error:
        print(f"ERROR: cannot read {source}: {error}")
        return 1

    # Canonicalize before measuring. The matcher only ever compares
    # alphanumeric runs, so a term must be stored the same way: folding
    # makes 'zqhàte' six characters, and stripping makes a two-word term
    # like 'go away' the single token the substring pass can actually
    # find. A term left punctuated here would be a digest nothing can
    # ever match.
    terms = {
        strip_nonalnum(normalize(stripped))
        for stripped in (line.strip() for line in raw.splitlines())
        if stripped and not stripped.startswith("#")
    }
    terms.discard("")
    if not terms:
        print("ERROR: no terms found")
        return 1

    lengths = [len(term) for term in terms]
    header = (f"# minlen={min(lengths)} maxlen={max(lengths)} "
              f"substr_minlen={SUBSTR_MINLEN}")

    lines = [header,
             "# Generated by scripts/hash_terms.py. Do not edit by hand."]
    lines += sorted({digest(term) for term in terms})

    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines) - 2} digests to {dest} ({header})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
